name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-main, api-search ]
    defaults:
      run:
        working-directory: services/${{ matrix.service }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            services/api-main/package-lock.json
            services/api-search/package-lock.json

      - name: Install deps (incluye devDependencies)
        env:
          NODE_ENV: ""
        run: npm i

      - name: Run tests
        env:
          CI: "true"
        run: npm test
